# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Setup Rust Toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true

    - run: npm ci
    - run: npm run tauri build
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: swtor-chat-artifacts
        path: |
          ./src-tauri/target/release/SWTOR-Chat.exe
          ./src-tauri/target/release/swtor_chat_capture.dll
          ./src-tauri/target/release/sql/**/*
